import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
	return (
		<div>
			<Head>
				<title>Linkedin | Built By Raga Jai Santhosh</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</div>
	)
}
